profile: private
region: us-east-1
configuration:
  name: lamvery-test-js
  runtime: nodejs
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: lambda_function.lambdaHandler
  description: This is sample lambda function.
  timeout: 10
  memory_size: 128
events:
  - rule: foo
    description: bar
    schedule: 'rate(5 minutes)'
    targets:
    - id: test-target-id
      input:
        this:
        - is: a
        - sample: input
secret:
  key_id: {{ env['AWS_KMS_KEY_ID'] }}
  cipher_texts:
    foo: CiC4xW9lg7HaxaueeN+d9yJMyY1uw1i7tYVvQz9I8+e2UBKVAQEBAgB4uMVvZYOx2sWrnnjfnfciTMmNbsNYu7WFb0M/SPPntlAAAABsMGoGCSqGSIb3DQEHBqBdMFsCAQAwVgYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwN5YM9tDwY/TItbG8CARCAKW1+6MfloCrykA+gT1roV1IoZPt3dsfoJQEJNWPQ83/Cj1b7Om22Pboz
exclude:
- ^\.lamvery\.yml$
