profile: null
configuration:
  region: us-east-1
  name: lambery
  runtime: python2.7
  role: arn:aws:iam::<account-number>:role/<role>
  handler: lambda_function.lambda_handler
  description: This is sample lambda function.
  timeout: 10
  memory_size: 128
secret:
  key: <key-id>
  cipher_texts: {}
