language: python
env:
  - AWS_REGION=us-east-1
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: "nosetests -v --with-coverage --cover-package=lamvery"
after_success: coveralls
